# Generated by Django 3.2 on 2023-11-17 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad_pasajeros', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
            },
        ),
        migrations.CreateModel(
            name='TarjetaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tarjeta', models.CharField(max_length=20, unique=True)),
                ('clave_tarjeta', models.CharField(max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'TarjetaTransporte',
                'verbose_name_plural': 'TarjetaTransportes',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('costo_tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAdmin.bus')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAdmin.pasajero')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
            },
        ),
        migrations.AddField(
            model_name='pasajero',
            name='tarjeta_transporte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestionAdmin.tarjetatransporte'),
        ),
        migrations.AddField(
            model_name='bus',
            name='pasajeros',
            field=models.ManyToManyField(through='GestionAdmin.Viaje', to='GestionAdmin.Pasajero'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
