name: Testing strategy matrix in github actions

on:
  push:
    branches:
      - "main"

jobs:
  python_tests:
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        # Installing wheel package will slightly speed-up installing dependencies.
        # Installing the package with "[dev]" flag  will install test dependecies as well,
        # enabling us to run pytest.
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install .[dev]


