name: Build and Deploy

on:
  push:
    branches: [ master ]
  
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test
        run: |
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_test]    
    steps:
      - name: echo hello world
        run: echo "Hello, World!"
        